### ISSUE TITLE
Always show error ": No such file or directory"

### ISSUE THREAD

**Issue by halink0803** [JohnByrneRepo/mddir#5]
No matter what path I used (current folder, relative path or absolute path), mddir always show ": No such file or directory".

**Comment by halink0803** [comment]
Srr, I misunderstood the usage of the package. I need to change directory into "node_modules/mddir/src" in order to run the package. It works, however needing to add more options to generate folder only or some type of files only. Nice plugins anw. 

Thanks,

**Comment by JohnByrneRepo** [comment]
Thanks for your good feedback. You should install the module globally so that you can use it from anywhere, this is in the readme:

npm install -g mddir

Then to run it:

mddir './'
